### ISSUE TITLE
Error: Cannot read property  "emit" of undefined 

### ISSUE THREAD

**Issue by Fidelitho** [Spruik/Libre-Downtime-Pie-Chart-Panel#4]
Hi,

I was able to install it on my grafana running on version 7.1.5 and when I try to use it I get the error below:

![image](https://user-images.githubusercontent.com/49202470/91999549-6096f200-ecf1-11ea-8aaf-901c63cafd32.png)

thank you.

**Comment by tomhollingworth** [comment]
@Fidelitho plugins were built for Grafana 6.x.x. I'll update the readme to reflect this. We are working on 7.x.x plugins but Grafana has changed their javascript framework over to React from Angular so this may take some time.
